version: "2.2"

services:
  openhab:
    image: "openhab/openhab:2.5.0"
    container_name: openhab
    restart: always
    volumes:
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/openhab_addons:/openhab/addons"
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/openhab_conf:/openhab/conf"
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      USER_ID: 1000
      GROUP_ID: 1000
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
    ports:
      - "8080:8080"
      - "8443:8443"
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "25826:25826/udp"
      - "2003:2003"
    env_file:
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/env.influxdb"
    volumes:
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/influxdb/data:/var/lib/influxdb/"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "1000:1000"
    ports:
      - "3000:3000"
    env_file:
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/env.grafana"
    volumes:
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/grafana/data:/var/lib/grafana/"
  nodered:
    image: nodered/node-red-docker:latest
    container_name: nodered
    restart: always
    user: root
    ports:
      - "1880:1880"
    volumes:
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/nodered:/data"
  frontail:
    image: mthenw/frontail
    container_name: frontail
    restart: unless-stopped
    command: --disable-usage-stats -l 2000 -n 200 /logs/logs/openhab.log /logs/logs/events.log
    # after start and migratin of files:  command: --disable-usage-stats --ui-highlight --ui-highlight-preset /frontail/preset/openhab.json -t openhab -l 2000 -n 200 /logs/logs/openhab.log /logs/logs/events.log
    depends_on:
      - openhab
    volumes:
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/frontail/preset.json:/frontail/preset/openhab.json:ro"
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/frontail/openhab.css:/frontail/web/assets/styles/openhab.css:ro"
      - "C:/Users/billr/Documents/GitHub/OpenHAB_Stack/openhab_userdata/logs:/logs:ro"
    ports:
      - "9001:9001"