version: '2'
volumes:
  openhab-conf:
    driver: rancher-nfs
  grafana-data:
    driver: rancher-nfs
  openhab-userdata:
    driver: rancher-nfs
  chronograf-data:
    driver: rancher-nfs
  frontail-web:
    driver: rancher-nfs
  frontail-presets:
    driver: rancher-nfs
  openhab-addons:
    driver: rancher-nfs
  influxdb-data:
    driver: rancher-nfs
  nodered-data:
    driver: rancher-nfs
services:
  OpenHAB:
    image: openhab/openhab:2.5.1
    environment:
      EXTRA_JAVA_OPTS: -Duser.timezone=America/Los_Angeles
      GROUP_ID: '2000'
      OPENHAB_HTTPS_PORT: '8443'
      OPENHAB_HTTP_PORT: '8080'
      USER_ID: '2000'
    volumes:
    - openhab-addons:/openhab/addons
    - openhab-conf:/openhab/conf
    - openhab-userdata:/openhab/userdata
    ports:
    - 8081:8080/tcp
    - 8444:8443/tcp
    - 9110:9110/tcp
  Chronograf:
    image: chronograf:1.5
    stdin_open: true
    volumes:
    - chronograf-data:/var/lib/chronograf
    tty: true
    ports:
    - 8888:8888/tcp
    command:
    - --influxdb-url=http:/192.168.2.81:8086
    labels:
      io.rancher.container.pull_image: always
  InfluxDB:
    image: influxdb:latest
    environment:
      INFLUXDB_ADMIN_PASSWORD: '123456789'
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_DB: openhab_db
      INFLUXDB_READ_USER: '"openhab_ro"'
      INFLUXDB_READ_USER_PASSWORD: '123456789'
      INFLUXDB_REPORTING_DISABLED: 'false'
      INFLUXDB_USER: openhab
      INFLUXDB_USER_PASSWORD: '123456789'
    volumes:
    - influxdb-data:/var/lib/influxdb/
    ports:
    - 8083:8083/tcp
    - 8086:8086/tcp
    - 8090:8090/tcp
    - 25826:25826/udp
    - 2003:2003/tcp
  Grafana:
    image: grafana/grafana:latest
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    volumes:
    - grafana-data:/var/lib/grafana/
    ports:
    - 3000:3000/tcp
    user: '472'
  Frontail:
    image: mthenw/frontail:latest
    volumes:
    - frontail-presets:/frontail/preset/
    - frontail-web:/frontail/web/assets/styles/
    - openhab-userdata:/logs:ro
    ports:
    - 9002:9001/tcp
    command:
    - --disable-usage-stats
    - --ui-highlight
    - --ui-highlight-preset
    - /frontail/preset/openhab.json
    - -t
    - openhab
    - -l
    - '2000'
    - -n
    - '200'
    - /logs/logs/openhab.log
    - /logs/logs/events.log
  NodeRed:
    image: nodered/node-red-docker:latest
    volumes:
    - nodered-data:/data
    ports:
    - 1880:1880/tcp
    user: root